test: reproduce metro issue
If you run all instrumentation tests you get something similar to:

```
java.lang.IllegalAccessError: Illegal class access: 'com.youniqx.package.app.ui.download.DownloadTests' attempting to access 'com.youniqx.package.app.ui.AppTests$DynamicAppGraphImpl_Y8lEdMM$FactoryImpl' (declaration of 'com.youniqx.package.app.ui.download.DownloadTests' appears in /data/app/~~viQFO6H120KhW1_MhJo-UA==/com.youniqx.package.app.test-fUcghD7NWmvfZ-rE_bcSjA==/base.apk!classes14.dex)
at com.youniqx.package.app.ui.download.DownloadTests.<init>(DownloadTests.kt:51)
```

If the AppTests file is deleted the error gets:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/youniqx/package/app/ui/AppTests$DynamicAppGraphImpl_Y8lEdMM$FactoryImpl;
at com.youniqx.package.app.ui.download.DownloadTests.<init>(DownloadTests.kt:51)
... 32 trimmed
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.youniqx.package.app.ui.AppTests$DynamicAppGraphImpl_Y8lEdMM$FactoryImpl" on path: DexPathList[[zip file "/data/app/~~EZ5T-8fSDlbhtiPHlsvgpw==/com.youniqx.package.app.test-l_8faolRp-q5vrzWlcpYpg==/base.apk"],nativeLibraryDirectories=[/data/app/~~EZ5T-8fSDlbhtiPHlsvgpw==/com.youniqx.package.app.test-l_8faolRp-q5vrzWlcpYpg==/lib/arm64, /data/app/~~EZ5T-8fSDlbhtiPHlsvgpw==/com.youniqx.package.app.test-l_8faolRp-q5vrzWlcpYpg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
```